
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightPOWERleftSINCOSTANLOGEXPCOS DIVIDE EXP LOG LPAREN MINUS NUMBER PLUS POWER RPAREN SIN TAN TIMESexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression POWER expressionexpression : MINUS expression %prec MINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : SIN LPAREN expression RPARENexpression : COS LPAREN expression RPARENexpression : TAN LPAREN expression RPARENexpression : LOG LPAREN expression RPARENexpression : EXP LPAREN expression RPAREN'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,],[2,11,2,2,-8,2,2,2,2,2,-6,11,2,2,2,2,2,-1,-2,-3,-4,-5,-7,11,11,11,11,11,-9,-10,-11,-12,-13,]),'LPAREN':([0,2,3,5,6,7,8,9,10,11,12,13,14,17,18,19,20,21,],[3,3,3,17,18,19,20,21,3,3,3,3,3,3,3,3,3,3,]),'NUMBER':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[4,4,4,4,4,4,4,4,4,4,4,4,4,]),'SIN':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[5,5,5,5,5,5,5,5,5,5,5,5,5,]),'COS':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'TAN':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[7,7,7,7,7,7,7,7,7,7,7,7,7,]),'LOG':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[8,8,8,8,8,8,8,8,8,8,8,8,8,]),'EXP':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[9,9,9,9,9,9,9,9,9,9,9,9,9,]),'$end':([1,4,15,22,23,24,25,26,27,33,34,35,36,37,],[0,-8,-6,-1,-2,-3,-4,-5,-7,-9,-10,-11,-12,-13,]),'PLUS':([1,4,15,16,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,],[10,-8,-6,10,-1,-2,-3,-4,-5,-7,10,10,10,10,10,-9,-10,-11,-12,-13,]),'TIMES':([1,4,15,16,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,],[12,-8,12,12,12,12,-3,-4,-5,-7,12,12,12,12,12,-9,-10,-11,-12,-13,]),'DIVIDE':([1,4,15,16,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,],[13,-8,13,13,13,13,-3,-4,-5,-7,13,13,13,13,13,-9,-10,-11,-12,-13,]),'POWER':([1,4,15,16,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,],[14,-8,14,14,14,14,14,14,14,-7,14,14,14,14,14,-9,-10,-11,-12,-13,]),'RPAREN':([4,15,16,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,],[-8,-6,27,-1,-2,-3,-4,-5,-7,33,34,35,36,37,-9,-10,-11,-12,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,10,11,12,13,14,17,18,19,20,21,],[1,15,16,22,23,24,25,26,28,29,30,31,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',15),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',16),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',17),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',18),
  ('expression -> expression POWER expression','expression',3,'p_expression_binop','parser.py',19),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',34),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',38),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',42),
  ('expression -> SIN LPAREN expression RPAREN','expression',4,'p_expression_sin','parser.py',46),
  ('expression -> COS LPAREN expression RPAREN','expression',4,'p_expression_cos','parser.py',50),
  ('expression -> TAN LPAREN expression RPAREN','expression',4,'p_expression_tan','parser.py',54),
  ('expression -> LOG LPAREN expression RPAREN','expression',4,'p_expression_log','parser.py',58),
  ('expression -> EXP LPAREN expression RPAREN','expression',4,'p_expression_exp','parser.py',64),
]
